# Generated by Django 5.2.6 on 2025-09-13 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options_remove_articles_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публікації'),
        ),
    ]
